ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongod-{{ env }}.naren83.online
REDIS_HOST: redis-{{ env }}.naren83.online
MYSQL_HOST: mysql-{{ env }}.naren83.online
RABBITMQ_HOST: rabbitmq-{{ env }}.naren83.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.naren83.online
USER_HOST: user.backend-alb-{{ env }}.naren83.online
CART_HOST: cart.backend-alb-{{ env }}.naren83.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.naren83.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.naren83.online
app_version: v3